---
# configuring apt-proxy

- name: Configuring apt directory for proxy
  template: >
    src:  "/etc/apt/apt.conf.d/{{ ubuntu-proxy-fix }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ ubuntu-proxy-fix }}"
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - apt-proxy
